"""A Python library for the TargetProcess v1 REST API."""

from targetprocess._observability import (
    REQUEST_ID_HEADER,
    ScrubbingFilter,
    StructuredJsonFormatter,
    current_request_id,
    get_logger,
    new_request_id,
    request_id_context,
)
from targetprocess.client import TargetProcessClient
from targetprocess.exceptions import (
    AmbiguousMatchError,
    APIError,
    AuthenticationError,
    ForbiddenError,
    NetworkError,
    NotFoundError,
    ParseError,
    RateLimitError,
    ReadOnlyViolation,
    RequestValidationError,
    TargetProcessError,
)
from targetprocess.models import (
    AssignableEntity,
    Assignment,
    Attachment,
    Bug,
    Comment,
    CustomActivity,
    CustomField,
    CustomFieldConfig,
    CustomFieldValue,
    CustomRule,
    Entity,
    EntityRef,
    EntityState,
    EntityType,
    EntityTypeRef,
    Epic,
    Feature,
    GeneralEntity,
    Iteration,
    NamedEntity,
    Priority,
    Process,
    Project,
    RefWithImportance,
    Relation,
    RelationType,
    Release,
    Request,
    Role,
    RoleEffort,
    Severity,
    Task,
    Team,
    TeamAssignment,
    TeamIteration,
    Term,
    TestCase,
    Time,
    UploadedAttachment,
    UploadedFileRef,
    User,
    UserRef,
    UserStory,
    Workflow,
)
from targetprocess.request_handler import RequestHandler
from targetprocess.resources import (
    AssignmentsResource,
    AttachmentsResource,
    BaseResource,
    BugsResource,
    CommentsResource,
    CustomActivitiesResource,
    CustomFieldsResource,
    CustomRulesResource,
    EntitiesResource,
    EntityStatesResource,
    EntityTypesResource,
    EpicsResource,
    FeaturesResource,
    IterationsResource,
    PrioritiesResource,
    ProcessesResource,
    ProjectsResource,
    RelationsResource,
    RelationTypesResource,
    ReleasesResource,
    RequestsResource,
    RoleEffortsResource,
    RolesResource,
    SeveritiesResource,
    TasksResource,
    TeamAssignmentsResource,
    TeamIterationsResource,
    TeamsResource,
    TermsResource,
    TestCasesResource,
    TimesResource,
    UsersResource,
    UserStoriesResource,
    WorkflowsResource,
)
from targetprocess.response_parser import ResponseParser
from targetprocess.types import ClientMode, UpsertAction, UpsertResult

__version__ = "0.1.0"

__all__ = [
    # Exceptions
    "AmbiguousMatchError",
    "APIError",
    "AuthenticationError",
    "ForbiddenError",
    "NetworkError",
    "NotFoundError",
    "ParseError",
    "RateLimitError",
    "ReadOnlyViolation",
    "RequestValidationError",
    "TargetProcessError",
    # Models - Base
    "Entity",
    "NamedEntity",
    "GeneralEntity",
    "AssignableEntity",
    "EntityRef",
    "EntityTypeRef",
    "UserRef",
    "RefWithImportance",
    # Models - Assignable
    "Bug",
    "Epic",
    "Feature",
    "Request",
    "Task",
    "TestCase",
    "UserStory",
    # Models - Planning
    "Iteration",
    "Release",
    # Models - Organizational
    "Project",
    "Team",
    "User",
    # Models - Workflow and configuration
    "EntityState",
    "Priority",
    "RelationType",
    "Role",
    "Severity",
    "Process",
    "Workflow",
    "EntityType",
    "Term",
    "CustomActivity",
    "CustomRule",
    # Models - Join
    "TeamIteration",
    "Assignment",
    "TeamAssignment",
    "Relation",
    "RoleEffort",
    "Time",
    # Models - Supporting
    "Comment",
    "Attachment",
    "UploadedAttachment",
    "UploadedFileRef",
    # Models - Custom fields
    "CustomField",
    "CustomFieldConfig",
    "CustomFieldValue",
    # Observability - structured logging, log scrubbing, request-ID propagation
    "REQUEST_ID_HEADER",
    "ScrubbingFilter",
    "StructuredJsonFormatter",
    "current_request_id",
    "get_logger",
    "new_request_id",
    "request_id_context",
    # Core Components
    "ClientMode",
    "RequestHandler",
    "ResponseParser",
    "TargetProcessClient",
    "UpsertAction",
    "UpsertResult",
    # Resource Managers - Base
    "BaseResource",
    # Resource Managers - Typed
    "AssignmentsResource",
    "AttachmentsResource",
    "BugsResource",
    "CommentsResource",
    "CustomActivitiesResource",
    "CustomFieldsResource",
    "CustomRulesResource",
    "EntityStatesResource",
    "EntityTypesResource",
    "EpicsResource",
    "FeaturesResource",
    "IterationsResource",
    "PrioritiesResource",
    "ProcessesResource",
    "ProjectsResource",
    "RelationTypesResource",
    "RelationsResource",
    "ReleasesResource",
    "RequestsResource",
    "RoleEffortsResource",
    "RolesResource",
    "SeveritiesResource",
    "TasksResource",
    "TeamAssignmentsResource",
    "TeamIterationsResource",
    "TeamsResource",
    "TermsResource",
    "TestCasesResource",
    "TimesResource",
    "UserStoriesResource",
    "UsersResource",
    "WorkflowsResource",
    # Resource Managers - Generic
    "EntitiesResource",
]
